<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

function wasl_drawMenu($container)
{
    echo  '<ul class="nav navbar-nav " >';
    foreach ($container as $page):
        echo '<li class="'.($page->hasPages() ? 'dropdown wasl-dropdown' : '' ).'">';
        echo '<a href="'.($page->getHref()).'" target="'.($page->getTarget()).'">';
            echo $page->getLabel();
            if ($page->hasPages()):
                echo '<span class="caret"></span>';
            endif;
        echo '</a';
        
            
    endforeach;
    
}

?>
<!--<nav class="navbar navbar-inverse">-->

    <ul class="nav navbar-nav " >
        <?php foreach ($this->container as $page):
            /** @var Zend\Navigation\Page\AbstractPage $page */ ?>    
       
            <li class="<?php echo $page->hasPages() ? 'dropdown wasl-dropdown' : '' ?>">
            <a href="<?php echo $page->getHref() ?>" target="<?php echo $page->getTarget() ?>"
                <?php  //echo $page->hasPages() ? 'class="dropdown-toggle" data-toggle="dropdown" ' : '' ?>>
                <?php echo $page->getLabel() ?>
                <?php if ($page->hasPages()): ?>
                    <span class="caret"></span>
                <?php endif; ?>
            </a>
            <?php if ($page->hasPages()): ?>
                <ul class="dropdown-menu">
                    <?php foreach ($page->getPages() as $child):
                        /** @var Zend\Navigation\Page\AbstractPage $child */ ?>
                        <li >
                            <a href="<?php echo $child->getHref() ?>">
                                <?php echo $child->getLabel() ?>
                            </a>
                        </li>
                    <?php endforeach; ?>
                </ul>
            <?php endif; ?>
            </li>       
        <?php endforeach; ?>
    </li
    </ul>

<!--</nav>-->

