<?php // in module/Application/view/partial/paginatorkolory.phtml: ?>
<?php if ($this->pageCount): ?>
<div>
  <ul class="pagination">
      
      <!--poczatek listy-->
   <li >
       <a href="javascript:void(0);" onclick="getKolorPage(1)">
            &lt;&lt;
        </a>
   </li>
      
  <!-- Previous page link -->
  <?php if (isset($this->previous)): ?>
    <li>
      <a href="javascript:void(0);" onclick="getKolorPage(  <?=$this->previous; ?>)">
        &lt;
      </a>
    </li>
  <?php else: ?>
    <li class="disabled">
      <a href="#">
        &lt;
      </a>
    </li>
  <?php endif ?>

  <!-- Numbered page links -->
  <?php foreach ($this->pagesInRange as $page): ?>
    <?php if ($page !== $this->current): ?>
      <li>
        <a href="javascript:void(0);" onclick="getKolorPage(  <?=$page; ?>)">
          <?= $page ?>
        </a>
      </li>
    <?php else: ?>
      <li class="active">
        <a href="#"><?= $page ?></a>
      </li>
    <?php endif ?>
  <?php endforeach ?>

  <!-- Next page link -->
  <?php if (isset($this->next)): ?>
    <li>
      <a href="javascript:void(0);" onclick="getKolorPage(  <?=$this->next; ?>)">
        &gt;
      </a>
    </li>
  <?php else: ?>
    <li class="disabled">
      <a href="javascript:void(0);">
        &gt;
      </a>
    </li>
  <?php endif ?>
    <!--koniec listy-->
     <li >
      <a href="javascript:void(0);" onclick="getKolorPage(  <?=$this->pageCount; ?>)">
        &gt;&gt;
      </a>
    </li>
  </ul>
</div>
<?php endif ?>