<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */




$title = 'Nowa rola';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<?php

$rola = $form->get('role');
$rola->setAttribute('class', 'form-control');
$rola->setAttribute('placeholder', 'Rola');

$select = $form->get('parent_role');
$select->setAttribute('class', 'form-control');
$select->setAttribute('placeholder', 'Parent_role');

//$parent_role = $form->get('arent_role');
//$parent_role->setAttribute('class', 'form-control');
//$parent_role->setAttribute('placeholder', 'Rola nadrzędna');

$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$cancel = $form->get('cancel');
$cancel->setAttribute('class', 'btn btn-secondary');

$form->setAttribute('action', $this->url('admin', ['action' => 'addrole']));
$form->prepare();

echo $this->form()->openTag($form);
?>
<?php // Wrap the elements in divs marked as form groups, and render the
      // label, element, and errors separately within ?>


<div class="form-group">
    <?= $this->formLabel($rola) ?>
    <?= $this->formElement($rola) ?>
    <?= $this->formElementErrors()->render($rola, ['class' => 'help-block']) ?>
</div>


<div class="form-group">
    <?= $this->formLabel($select) ?>
    <?= $this->formElement($select) ?>
     <?= $this->formElementErrors()->render($select, ['class' => 'help-block']) ?>
 
</div>

<div class="form-group">
    <?= $this->formSubmit($submit);?>
    <?=  $this->formSubmit($cancel) ?>
</div>
<?php
echo $this->formHidden($form->get('id'));

echo $this->form()->closeTag();