<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */




$title = 'Nowy użytkownik';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<?php

$login = $form->get('login');
$login->setAttribute('class', 'form-control');
$login->setAttribute('placeholder', 'Login');

$password = $form->get('password');
$password->setAttribute('class', 'form-control');
$password->setAttribute('placeholder', 'Hasło');

$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$cancel = $form->get('cancel');
$cancel->setAttribute('class', 'btn btn-secondary');

$form->setAttribute('action', $this->url('admin', ['action' => 'adduser']));
$form->prepare();

echo $this->form()->openTag($form);
?>
<?php // Wrap the elements in divs marked as form groups, and render the
      // label, element, and errors separately within ?>


<div class="form-group">
    <?= $this->formLabel($login) ?>
    <?= $this->formElement($login) ?>
    <?= $this->formElementErrors()->render($login, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($password) ?>
    <?= $this->formElement($password) ?>
    <?= $this->formElementErrors()->render($password, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formSubmit($submit);?>
    <?=  $this->formSubmit($cancel) ?>
</div>
<?php
echo $this->formHidden($form->get('id'));

echo $this->form()->closeTag();