<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

$title = 'Edytuj rolę';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<?php
$rola = $form->get('role');
$rola->setAttribute('class', 'form-control');
$rola->setAttribute('placeholder', 'Rola');

$select = $form->get('parent_role');
$select->setAttribute('class', 'form-control');
$select->setAttribute('placeholder', 'Rola nadrzędna');

$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$cancel = $form->get('cancel');
$cancel->setAttribute('class', 'btn btn-secondary');

$form->setAttribute('action', $this->url('admin', [
    'action' => 'editrole',
    'id'     => $id,
]));
$form->prepare();

echo $this->form()->openTag($form);
?>
<div class="form-group">
    <?= $this->formLabel($rola) ?>
    <?= $this->formElement($rola) ?>
    <?= $this->formElementErrors()->render($rola, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($select) ?>
    <?= $this->formElement($select) ?>
    <?= $this->formElementErrors()->render($select, ['class' => 'help-block']) ?>
</div>


<div class="form-group">
    <?=  $this->formSubmit($submit) ?>
    <?=  $this->formSubmit($cancel) ?>
    <?=  $this->formHidden($form->get('id')) ?>
</div>
<?php
echo $this->form()->closeTag();