<?php



$title = 'Logowanie do systemu';
$this->headTitle($title);
?>
<center><h1><?= $this->escapeHtml($title) ?></h1></center>


<div class='container' style='margin-top: 50px;'>
    
<div class="row">
    <div class="col-sm-4">&nbsp;</div>
    <div class="col-sm-4">
<?php

$login = $form->get('user');
$login->setAttribute('class', 'form-control');
//$login->setAttribute('placeholder', 'Login');

$password = $form->get('password');
$password->setAttribute('class', 'form-control');
$password->setAttribute('placeholder', 'Password');

$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$cancel = $form->get('cancel');
$cancel->setAttribute('class', 'btn btn-secondary');

$form->setAttribute('action', $this->url('admin', ['action' => 'login']));
$form->prepare();

echo $this->form()->openTag($form);
?>
<?php // Wrap the elements in divs marked as form groups, and render the
      // label, element, and errors separately within ?>
<div class="form-group">
    <?= $this->formLabel($login) ?>
    <?= $this->formElement($login) ?>
    <?= $this->formElementErrors()->render($login, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($password) ?>
    <?= $this->formElement($password) ?>
    <?= $this->formElementErrors()->render($password, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formSubmit($submit);?>
    <?=  $this->formSubmit($cancel) ?>
</div>
<?php
echo $this->form()->closeTag(); ?>

    </div>
     <div class="col-sm-4">&nbsp;</div>    
</div>
</div>
