<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */




$title = 'Add new kolor';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<?php

$kolor = $form->get('kolor');
$kolor->setAttribute('class', 'form-control');
$kolor->setAttribute('placeholder', 'kolor');

$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$cancel = $form->get('cancel');
$cancel->setAttribute('class', 'btn btn-secondary');

$form->setAttribute('action', $this->url('album', ['action' => 'addKolor']));
$form->prepare();

echo $this->form()->openTag($form);
?>
<?php // Wrap the elements in divs marked as form groups, and render the
      // label, element, and errors separately within ?>


<div class="form-group">
    <?= $this->formLabel($kolor) ?>
    <?= $this->formElement($kolor) ?>

</div>

<div class="form-group">
    <?= $this->formSubmit($submit);?>
    <?=  $this->formSubmit($cancel) ?>
</div>
<?php
echo $this->formHidden($form->get('id'));
echo $this->formHidden($form->get('idAlbum'));
echo $this->form()->closeTag();